# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'streamchain' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for streamchain
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'ART',
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'RCTLinkingIOS',
      'RCTAnimation',
      'RCTAdSupport',
      'RCTCameraRoll',
      'RCTPushNotification',
      'RCTSettings'
    ]
  pod 'PLMediaStreamingKit'
  pod 'PLPlayerKit'
  pod 'HappyDNS'
  pod 'RCTPili', :path => '../node_modules/react-native-pili/ios/RCTPili'

end
